#define private public
#define protected public
/*
 *  Delphes: a framework for fast simulation of a generic collider experiment
 *  Copyright (C) 2012-2014  Universite catholique de Louvain (UCL), Belgium
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/** \class
 *
 *  Lists classes to be included in cint dicitonary
 *
 *  \author P. Demin - UCL, Louvain-la-Neuve
 *
 */

#include "modules/FastJetFinder.h"
#include "modules/FastJetGridMedianEstimator.h"

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class FastJetFinder+;
#pragma link C++ class FastJetGridMedianEstimator+;

#endif
//
// File generated by rootcint at Wed Jul  1 00:17:24 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME tmpdImodulesdIFastJetDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "FastJetDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void FastJetFinder_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_FastJetFinder(void *p = 0);
   static void *newArray_FastJetFinder(Long_t size, void *p);
   static void delete_FastJetFinder(void *p);
   static void deleteArray_FastJetFinder(void *p);
   static void destruct_FastJetFinder(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::FastJetFinder*)
   {
      ::FastJetFinder *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::FastJetFinder >(0);
      static ::ROOT::TGenericClassInfo 
         instance("FastJetFinder", ::FastJetFinder::Class_Version(), "./modules/FastJetFinder.h", 47,
                  typeid(::FastJetFinder), DefineBehavior(ptr, ptr),
                  &::FastJetFinder::Dictionary, isa_proxy, 4,
                  sizeof(::FastJetFinder) );
      instance.SetNew(&new_FastJetFinder);
      instance.SetNewArray(&newArray_FastJetFinder);
      instance.SetDelete(&delete_FastJetFinder);
      instance.SetDeleteArray(&deleteArray_FastJetFinder);
      instance.SetDestructor(&destruct_FastJetFinder);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::FastJetFinder*)
   {
      return GenerateInitInstanceLocal((::FastJetFinder*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FastJetFinder*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void FastJetGridMedianEstimator_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_FastJetGridMedianEstimator(void *p = 0);
   static void *newArray_FastJetGridMedianEstimator(Long_t size, void *p);
   static void delete_FastJetGridMedianEstimator(void *p);
   static void deleteArray_FastJetGridMedianEstimator(void *p);
   static void destruct_FastJetGridMedianEstimator(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::FastJetGridMedianEstimator*)
   {
      ::FastJetGridMedianEstimator *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::FastJetGridMedianEstimator >(0);
      static ::ROOT::TGenericClassInfo 
         instance("FastJetGridMedianEstimator", ::FastJetGridMedianEstimator::Class_Version(), "./modules/FastJetGridMedianEstimator.h", 42,
                  typeid(::FastJetGridMedianEstimator), DefineBehavior(ptr, ptr),
                  &::FastJetGridMedianEstimator::Dictionary, isa_proxy, 4,
                  sizeof(::FastJetGridMedianEstimator) );
      instance.SetNew(&new_FastJetGridMedianEstimator);
      instance.SetNewArray(&newArray_FastJetGridMedianEstimator);
      instance.SetDelete(&delete_FastJetGridMedianEstimator);
      instance.SetDeleteArray(&deleteArray_FastJetGridMedianEstimator);
      instance.SetDestructor(&destruct_FastJetGridMedianEstimator);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::FastJetGridMedianEstimator*)
   {
      return GenerateInitInstanceLocal((::FastJetGridMedianEstimator*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FastJetGridMedianEstimator*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *FastJetFinder::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *FastJetFinder::Class_Name()
{
   return "FastJetFinder";
}

//______________________________________________________________________________
const char *FastJetFinder::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FastJetFinder*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int FastJetFinder::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FastJetFinder*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void FastJetFinder::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FastJetFinder*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *FastJetFinder::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FastJetFinder*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *FastJetGridMedianEstimator::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *FastJetGridMedianEstimator::Class_Name()
{
   return "FastJetGridMedianEstimator";
}

//______________________________________________________________________________
const char *FastJetGridMedianEstimator::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FastJetGridMedianEstimator*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int FastJetGridMedianEstimator::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::FastJetGridMedianEstimator*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void FastJetGridMedianEstimator::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FastJetGridMedianEstimator*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *FastJetGridMedianEstimator::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::FastJetGridMedianEstimator*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void FastJetFinder::Streamer(TBuffer &R__b)
{
   // Stream an object of class FastJetFinder.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(FastJetFinder::Class(),this);
   } else {
      R__b.WriteClassBuffer(FastJetFinder::Class(),this);
   }
}

//______________________________________________________________________________
void FastJetFinder::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class FastJetFinder.
      TClass *R__cl = ::FastJetFinder::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPlugin", &fPlugin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRecomb", &fRecomb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fNjettinessPlugin", &fNjettinessPlugin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDefinition", &fDefinition);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fJetAlgorithm", &fJetAlgorithm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fParameterR", &fParameterR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fJetPTMin", &fJetPTMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fConeRadius", &fConeRadius);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSeedThreshold", &fSeedThreshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fConeAreaFraction", &fConeAreaFraction);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaxIterations", &fMaxIterations);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaxPairSize", &fMaxPairSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIratch", &fIratch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAdjacencyCut", &fAdjacencyCut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fOverlapThreshold", &fOverlapThreshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fComputeNsubjettiness", &fComputeNsubjettiness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBeta", &fBeta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAxisMode", &fAxisMode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRcutOff", &fRcutOff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fN", &fN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fAreaDefinition", &fAreaDefinition);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAreaAlgorithm", &fAreaAlgorithm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fComputeRho", &fComputeRho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGhostEtaMax", &fGhostEtaMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRepeat", &fRepeat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGhostArea", &fGhostArea);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGridScatter", &fGridScatter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPtScatter", &fPtScatter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMeanGhostPt", &fMeanGhostPt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEffectiveRfact", &fEffectiveRfact);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fItInputArray", &fItInputArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fInputArray", &fInputArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fOutputArray", &fOutputArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRhoOutputArray", &fRhoOutputArray);
      DelphesModule::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_FastJetFinder(void *p) {
      return  p ? new(p) ::FastJetFinder : new ::FastJetFinder;
   }
   static void *newArray_FastJetFinder(Long_t nElements, void *p) {
      return p ? new(p) ::FastJetFinder[nElements] : new ::FastJetFinder[nElements];
   }
   // Wrapper around operator delete
   static void delete_FastJetFinder(void *p) {
      delete ((::FastJetFinder*)p);
   }
   static void deleteArray_FastJetFinder(void *p) {
      delete [] ((::FastJetFinder*)p);
   }
   static void destruct_FastJetFinder(void *p) {
      typedef ::FastJetFinder current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::FastJetFinder

//______________________________________________________________________________
void FastJetGridMedianEstimator::Streamer(TBuffer &R__b)
{
   // Stream an object of class FastJetGridMedianEstimator.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(FastJetGridMedianEstimator::Class(),this);
   } else {
      R__b.WriteClassBuffer(FastJetGridMedianEstimator::Class(),this);
   }
}

//______________________________________________________________________________
void FastJetGridMedianEstimator::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class FastJetGridMedianEstimator.
      TClass *R__cl = ::FastJetGridMedianEstimator::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEstimators", (void*)&fEstimators);
      R__insp.InspectMember("vector<fastjet::GridMedianBackgroundEstimator*>", (void*)&fEstimators, "fEstimators.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fItInputArray", &fItInputArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fInputArray", &fInputArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRhoOutputArray", &fRhoOutputArray);
      DelphesModule::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_FastJetGridMedianEstimator(void *p) {
      return  p ? new(p) ::FastJetGridMedianEstimator : new ::FastJetGridMedianEstimator;
   }
   static void *newArray_FastJetGridMedianEstimator(Long_t nElements, void *p) {
      return p ? new(p) ::FastJetGridMedianEstimator[nElements] : new ::FastJetGridMedianEstimator[nElements];
   }
   // Wrapper around operator delete
   static void delete_FastJetGridMedianEstimator(void *p) {
      delete ((::FastJetGridMedianEstimator*)p);
   }
   static void deleteArray_FastJetGridMedianEstimator(void *p) {
      delete [] ((::FastJetGridMedianEstimator*)p);
   }
   static void destruct_FastJetGridMedianEstimator(void *p) {
      typedef ::FastJetGridMedianEstimator current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::FastJetGridMedianEstimator

/********************************************************
* tmp/modules/FastJetDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableFastJetDict();

extern "C" void G__set_cpp_environmentFastJetDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__cpp_reset_tagtableFastJetDict();
}
#include <new>
extern "C" int G__cpp_dllrevFastJetDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FastJetFinder */
static int G__FastJetDict_448_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FastJetFinder* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FastJetFinder[n];
     } else {
       p = new((void*) gvp) FastJetFinder[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FastJetFinder;
     } else {
       p = new((void*) gvp) FastJetFinder;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) FastJetFinder::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetFinder::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) FastJetFinder::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      FastJetFinder::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FastJetFinder*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetFinder::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FastJetFinder::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetFinder::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_448_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FastJetFinder::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__FastJetDict_448_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   FastJetFinder* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new FastJetFinder(*(FastJetFinder*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FastJetFinder G__TFastJetFinder;
static int G__FastJetDict_448_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FastJetFinder*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FastJetFinder*) (soff+(sizeof(FastJetFinder)*i)))->~G__TFastJetFinder();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FastJetFinder*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FastJetFinder*) (soff))->~G__TFastJetFinder();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* FastJetGridMedianEstimator */
static int G__FastJetDict_450_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FastJetGridMedianEstimator* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FastJetGridMedianEstimator[n];
     } else {
       p = new((void*) gvp) FastJetGridMedianEstimator[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FastJetGridMedianEstimator;
     } else {
       p = new((void*) gvp) FastJetGridMedianEstimator;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) FastJetGridMedianEstimator::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetGridMedianEstimator::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) FastJetGridMedianEstimator::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      FastJetGridMedianEstimator::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FastJetGridMedianEstimator*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetGridMedianEstimator::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FastJetGridMedianEstimator::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) FastJetGridMedianEstimator::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FastJetDict_450_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) FastJetGridMedianEstimator::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__FastJetDict_450_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   FastJetGridMedianEstimator* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new FastJetGridMedianEstimator(*(FastJetGridMedianEstimator*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FastJetGridMedianEstimator G__TFastJetGridMedianEstimator;
static int G__FastJetDict_450_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FastJetGridMedianEstimator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FastJetGridMedianEstimator*) (soff+(sizeof(FastJetGridMedianEstimator)*i)))->~G__TFastJetGridMedianEstimator();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FastJetGridMedianEstimator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FastJetGridMedianEstimator*) (soff))->~G__TFastJetGridMedianEstimator();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FastJetFinder */

/* FastJetGridMedianEstimator */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncFastJetDict {
 public:
  G__Sizep2memfuncFastJetDict(): p(&G__Sizep2memfuncFastJetDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncFastJetDict::*p)();
};

size_t G__get_sizep2memfuncFastJetDict()
{
  G__Sizep2memfuncFastJetDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceFastJetDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder))) {
     FastJetFinder *G__Lderived;
     G__Lderived=(FastJetFinder*)0x1000;
     {
       DelphesModule *G__Lpbase=(DelphesModule*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder),G__get_linked_tagnum(&G__FastJetDictLN_DelphesModule),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ExRootTask *G__Lpbase=(ExRootTask*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder),G__get_linked_tagnum(&G__FastJetDictLN_ExRootTask),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TTask *G__Lpbase=(TTask*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder),G__get_linked_tagnum(&G__FastJetDictLN_TTask),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder),G__get_linked_tagnum(&G__FastJetDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder),G__get_linked_tagnum(&G__FastJetDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator))) {
     FastJetGridMedianEstimator *G__Lderived;
     G__Lderived=(FastJetGridMedianEstimator*)0x1000;
     {
       DelphesModule *G__Lpbase=(DelphesModule*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator),G__get_linked_tagnum(&G__FastJetDictLN_DelphesModule),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ExRootTask *G__Lpbase=(ExRootTask*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator),G__get_linked_tagnum(&G__FastJetDictLN_ExRootTask),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TTask *G__Lpbase=(TTask*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator),G__get_linked_tagnum(&G__FastJetDictLN_TTask),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator),G__get_linked_tagnum(&G__FastJetDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator),G__get_linked_tagnum(&G__FastJetDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableFastJetDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString>",117,G__get_linked_tagnum(&G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString,less<TString> >",117,G__get_linked_tagnum(&G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<fastjet::GridMedianBackgroundEstimator*>",117,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FastJetFinder */
static void G__setup_memvarFastJetFinder(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder));
   { FastJetFinder *p; p=(FastJetFinder*)0x1000; if (p) { }
   G__memvar_setup((void*)0,89,0,0,-1,-1,-1,4,"fPlugin=",0,"!");
   G__memvar_setup((void*)0,89,0,0,-1,-1,-1,4,"fRecomb=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_fastjetcLcLcontribcLcLNjettinessPlugin),-1,-1,4,"fNjettinessPlugin=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_fastjetcLcLJetDefinition),-1,-1,4,"fDefinition=",0,"!");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fJetAlgorithm=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fParameterR=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fJetPTMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fConeRadius=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fSeedThreshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fConeAreaFraction=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fMaxIterations=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fMaxPairSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fIratch=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fAdjacencyCut=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fOverlapThreshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fComputeNsubjettiness=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBeta=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fAxisMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fRcutOff=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_fastjetcLcLAreaDefinition),-1,-1,4,"fAreaDefinition=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fAreaAlgorithm=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fComputeRho=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fGhostEtaMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fRepeat=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fGhostArea=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fGridScatter=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fPtScatter=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fMeanGhostPt=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fEffectiveRfact=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TIterator),-1,-1,4,"fItInputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__FastJetDictLN_TObjArray),-1,-1,4,"fInputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TObjArray),-1,-1,4,"fOutputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TObjArray),-1,-1,4,"fRhoOutputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* FastJetGridMedianEstimator */
static void G__setup_memvarFastJetGridMedianEstimator(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator));
   { FastJetGridMedianEstimator *p; p=(FastJetGridMedianEstimator*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR),G__defined_typename("vector<fastjet::GridMedianBackgroundEstimator*>"),-1,4,"fEstimators=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TIterator),-1,-1,4,"fItInputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__FastJetDictLN_TObjArray),-1,-1,4,"fInputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TObjArray),-1,-1,4,"fRhoOutputArray=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FastJetDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarFastJetDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFastJetFinder(void) {
   /* FastJetFinder */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder));
   G__memfunc_setup("FastJetFinder",1289,G__FastJetDict_448_0_1, 105, G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Finish",609,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__FastJetDict_448_0_5, 85, G__get_linked_tagnum(&G__FastJetDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&FastJetFinder::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__FastJetDict_448_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetFinder::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__FastJetDict_448_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&FastJetFinder::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__FastJetDict_448_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&FastJetFinder::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__FastJetDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__FastJetDict_448_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__FastJetDict_448_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetFinder::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__FastJetDict_448_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FastJetFinder::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__FastJetDict_448_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetFinder::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__FastJetDict_448_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FastJetFinder::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("FastJetFinder", 1289, G__FastJetDict_448_0_17, (int) ('i'), G__get_linked_tagnum(&G__FastJetDictLN_FastJetFinder), -1, 0, 1, 1, 1, 0, "u 'FastJetFinder' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FastJetFinder", 1415, G__FastJetDict_448_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncFastJetGridMedianEstimator(void) {
   /* FastJetGridMedianEstimator */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator));
   G__memfunc_setup("FastJetGridMedianEstimator",2621,G__FastJetDict_450_0_1, 105, G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Finish",609,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__FastJetDict_450_0_5, 85, G__get_linked_tagnum(&G__FastJetDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&FastJetGridMedianEstimator::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__FastJetDict_450_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetGridMedianEstimator::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__FastJetDict_450_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&FastJetGridMedianEstimator::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__FastJetDict_450_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&FastJetGridMedianEstimator::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__FastJetDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__FastJetDict_450_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__FastJetDict_450_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetGridMedianEstimator::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__FastJetDict_450_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FastJetGridMedianEstimator::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__FastJetDict_450_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&FastJetGridMedianEstimator::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__FastJetDict_450_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&FastJetGridMedianEstimator::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("FastJetGridMedianEstimator", 2621, G__FastJetDict_450_0_17, (int) ('i'), 
G__get_linked_tagnum(&G__FastJetDictLN_FastJetGridMedianEstimator), -1, 0, 1, 1, 1, 0, "u 'FastJetGridMedianEstimator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FastJetGridMedianEstimator", 2747, G__FastJetDict_450_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncFastJetDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalFastJetDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcFastJetDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__FastJetDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_TIterator = { "TIterator" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__FastJetDictLN_TTask = { "TTask" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR = { "map<TString,TString,less<TString>,allocator<pair<const TString,TString> > >" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_ExRootTask = { "ExRootTask" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_DelphesModule = { "DelphesModule" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_fastjet = { "fastjet" , 110 , -1 };
G__linked_taginfo G__FastJetDictLN_fastjetcLcLJetDefinition = { "fastjet::JetDefinition" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_fastjetcLcLAreaDefinition = { "fastjet::AreaDefinition" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontrib = { "fastjet::contrib" , 110 , -1 };
G__linked_taginfo G__FastJetDictLN_fastjetcLcLcontribcLcLNjettinessPlugin = { "fastjet::contrib::NjettinessPlugin" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_FastJetFinder = { "FastJetFinder" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_FastJetGridMedianEstimator = { "FastJetGridMedianEstimator" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR = { "vector<fastjet::GridMedianBackgroundEstimator*,allocator<fastjet::GridMedianBackgroundEstimator*> >" , 99 , -1 };
G__linked_taginfo G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<fastjet::GridMedianBackgroundEstimator*,allocator<fastjet::GridMedianBackgroundEstimator*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableFastJetDict() {
  G__FastJetDictLN_TClass.tagnum = -1 ;
  G__FastJetDictLN_TBuffer.tagnum = -1 ;
  G__FastJetDictLN_TMemberInspector.tagnum = -1 ;
  G__FastJetDictLN_TObject.tagnum = -1 ;
  G__FastJetDictLN_TNamed.tagnum = -1 ;
  G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FastJetDictLN_TObjArray.tagnum = -1 ;
  G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FastJetDictLN_TIterator.tagnum = -1 ;
  G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__FastJetDictLN_TTask.tagnum = -1 ;
  G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR.tagnum = -1 ;
  G__FastJetDictLN_ExRootTask.tagnum = -1 ;
  G__FastJetDictLN_DelphesModule.tagnum = -1 ;
  G__FastJetDictLN_fastjet.tagnum = -1 ;
  G__FastJetDictLN_fastjetcLcLJetDefinition.tagnum = -1 ;
  G__FastJetDictLN_fastjetcLcLAreaDefinition.tagnum = -1 ;
  G__FastJetDictLN_fastjetcLcLcontrib.tagnum = -1 ;
  G__FastJetDictLN_fastjetcLcLcontribcLcLNjettinessPlugin.tagnum = -1 ;
  G__FastJetDictLN_FastJetFinder.tagnum = -1 ;
  G__FastJetDictLN_FastJetGridMedianEstimator.tagnum = -1 ;
  G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR.tagnum = -1 ;
  G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableFastJetDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TIterator);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_TTask);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_ExRootTask);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_DelphesModule);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_fastjet);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_fastjetcLcLJetDefinition);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_fastjetcLcLAreaDefinition);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_fastjetcLcLcontrib);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_fastjetcLcLcontribcLcLNjettinessPlugin);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__FastJetDictLN_FastJetFinder),sizeof(FastJetFinder),-1,324864,(char*)NULL,G__setup_memvarFastJetFinder,G__setup_memfuncFastJetFinder);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__FastJetDictLN_FastJetGridMedianEstimator),sizeof(FastJetGridMedianEstimator),-1,324864,(char*)NULL,G__setup_memvarFastJetGridMedianEstimator,G__setup_memfuncFastJetGridMedianEstimator);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_vectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgR);
   G__get_linked_tagnum_fwd(&G__FastJetDictLN_reverse_iteratorlEvectorlEfastjetcLcLGridMedianBackgroundEstimatormUcOallocatorlEfastjetcLcLGridMedianBackgroundEstimatormUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupFastJetDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupFastJetDict()");
  G__set_cpp_environmentFastJetDict();
  G__cpp_setup_tagtableFastJetDict();

  G__cpp_setup_inheritanceFastJetDict();

  G__cpp_setup_typetableFastJetDict();

  G__cpp_setup_memvarFastJetDict();

  G__cpp_setup_memfuncFastJetDict();
  G__cpp_setup_globalFastJetDict();
  G__cpp_setup_funcFastJetDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncFastJetDict();
  return;
}
class G__cpp_setup_initFastJetDict {
  public:
    G__cpp_setup_initFastJetDict() { G__add_setup_func("FastJetDict",(G__incsetup)(&G__cpp_setupFastJetDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initFastJetDict() { G__remove_setup_func("FastJetDict"); }
};
G__cpp_setup_initFastJetDict G__cpp_setup_initializerFastJetDict;

